-- Creating a new database for SaaS analytics project
create database saas_analytics;

-- Select the database to work in
use saas_analytics;

-- Count total number of records in the customers table
SELECT COUNT(*) AS total_customers
FROM customers;
select * from customers;

-- Count total number of records in the marketing_spend table
SELECT COUNT(*) AS total_marketing_records
FROM marketing_spend;

-- Count total number of records in the monthly_activity table
SELECT COUNT(*) AS total_activity_records
FROM monthly_activity;

-- Count total number of records in the subscriptions table
SELECT COUNT(*) AS total_subscriptions
FROM subscriptions;

-- Count total number of records in the revenue table
SELECT COUNT(*) AS total_revenue_records
FROM revenue;



/*1-Monthly Customer Signups
 How many customers signed up each month?*/

select month(signup_date) as month ,
        year(signup_date) as year,
        count(customer_id) as total_signups
from customers
group by month(signup_date),year(signup_date)
order by year,month;



/*2-Customers by Acquisition Channel
Which marketing channel brings the most customers?
no. of customers acquired by each channel*/

select acquisition_channel,
       COUNT(customer_id) AS total_customers
from customers
group by acquisition_channel
order by total_customers desc;



/*3-Revenue by Plan Type
Revenue generated by each plan type*/

select plan_type,
	   sum(mrr) as total_revenue
from subscriptions
group by plan_type
order by total_revenue desc;



/*4-Average Sessions per Plan
Are higher plans more engaged?*/

SELECT 
    plan_type,
    AVG(sessions) AS avg_sessions
FROM monthly_activity
GROUP BY plan_type
ORDER BY avg_sessions DESC;


/*5-Active vs Inactive Customers
How many customers are active?*/

SELECT 
    COUNT(DISTINCT CASE WHEN is_active = 1 THEN customer_id END) AS active_customers,
    COUNT(DISTINCT CASE WHEN is_active = 0 THEN customer_id END) AS inactive_customers
FROM monthly_activity;





/*6-Churned Customers per Month
Percentage of customers who leave the service during a period
A churned customer is someone who stops using your product or service.*/
WITH months AS (
    SELECT DISTINCT DATE_FORMAT(start_date, '%Y-%m') AS month
    FROM subscriptions
),

active_customers AS (
    SELECT 
        m.month,
        COUNT(DISTINCT s.customer_id) AS active_customers
    FROM months m
    JOIN subscriptions s
        ON DATE_FORMAT(s.start_date, '%Y-%m') <= m.month
        AND (
            s.end_date IS NULL 
            OR DATE_FORMAT(s.end_date, '%Y-%m') >= m.month
        )
    GROUP BY m.month
),

churned_customers AS (
    SELECT 
        DATE_FORMAT(end_date, '%Y-%m') AS month,
        COUNT(DISTINCT customer_id) AS churned_customers
    FROM subscriptions
    WHERE end_date IS NOT NULL
    GROUP BY DATE_FORMAT(end_date, '%Y-%m')
)

SELECT 
    a.month,
    a.active_customers,
    COALESCE(c.churned_customers, 0) AS churned_customers,
    
    CONCAT(
        ROUND(
            COALESCE(c.churned_customers, 0) * 100.0 
            / NULLIF(a.active_customers, 0),
            2
        ),
        '%'
    ) AS churn_rate_percentage

FROM active_customers a
LEFT JOIN churned_customers c
    ON a.month = c.month
ORDER BY a.month;




/*7-Monthly Active Users (MAU) Trend*/

select 
	   DATE_FORMAT(month,'%Y-%m') AS month
       ,count(distinct customer_id) as MAU
from monthly_activity
where is_active ='True'
group by month;



/*8-CAC by Acquisition Channel (Customer Acquisition Cost)
how much marketing money is spent to acquire one customer.
CAC = Total Marketing Spend / Number of Customers Acquired*/

SELECT 
     c.acquisition_channel,
     ROUND(SUM(m.spend_amount) / COUNT(DISTINCT c.customer_id), 2) AS CAC
FROM customers AS c
JOIN marketing_spend AS m
ON c.acquisition_channel = m.channel
GROUP BY c.acquisition_channel
ORDER BY CAC desc;




/*9-LTV Calculation
LTV = total revenue earned from a customer during their lifetime*/
select customer_id,
       sum(mrr) as LTV
from subscriptions
group by customer_id
order by LTV desc;





/*10-Cohort Analysis
Goal: uper signup cohort.
Customer Retention – The percentage of existing customers who remain active over a certain period
Cohort = a group of users segmented based on similar event
idea:Group customers by the month they first signed up and track their activity over time.*/
WITH cohort_activity AS (
    SELECT customer_id,
           DATE_FORMAT(signup_date,'%y-%m') AS cohort_month
    FROM customers
),
activity_with_cohort AS (
    SELECT m.customer_id,
           m.month,
           m.is_active,
           cc.cohort_month,
           -- Calculate number of months since signup
           TIMESTAMPDIFF(MONTH, c.signup_date, m.month) AS cohort_index,     
           DATE_FORMAT(m.month, '%Y-%b') AS month_name,
           MONTH(m.month) AS month_number
    FROM monthly_activity m
    JOIN customers c
        ON m.customer_id = c.customer_id
    JOIN cohort_activity cc
        ON m.customer_id = cc.customer_id
)
SELECT cohort_month,
       month_name,
       month_number,
       cohort_index,
       COUNT(DISTINCT customer_id) AS active_customers
FROM activity_with_cohort
WHERE is_active = 1
GROUP BY cohort_month, month_name, month_number, cohort_index
ORDER BY cohort_month,month_number,cohort_index;




/*1️1 LTV by Acquisition Channel
Goal: See how much revenue each acquisition channel generates per customer.*/
WITH customer_ltv AS (
    SELECT customer_id,
           SUM(mrr) AS LTV
    FROM subscriptions
    GROUP BY customer_id
)
SELECT c.acquisition_channel,
       round(AVG(cl.LTV),2) AS avg_LTV,
       SUM(cl.LTV) AS total_LTV,
       count(cl.customer_id) as total_customers
FROM customer_ltv cl
JOIN customers c
    ON cl.customer_id = c.customer_id
GROUP BY c.acquisition_channel
ORDER BY total_LTV DESC;





/*12-Top plans by total MRR each month*/
select * from(SELECT 
     plan_type,
     DATE_FORMAT(start_date, '%Y-%m') AS month,
	 sum(mrr) as total_mrr,
     dense_rank()over(partition by DATE_FORMAT(start_date, '%Y-%m') order by sum(mrr) desc) as rnk
from subscriptions
group by  plan_type,  DATE_FORMAT(start_date, '%Y-%m')
)ranked
where rnk<=3
ORDER BY month, rnk;





/*13-Marketing Spend vs Revenue*/
Select m.month,
       round(sum(m.spend_amount))as total_marketing_spend,
       round(sum(r.total_mrr))as total_revenue
from marketing_spend as m
join revenue as r
on DATE_FORMAT(m.month, '%Y-%m') = DATE_FORMAT(r.month, '%Y-%m')
group by m.month
ORDER BY month;
       


